name: Create release

on:
  push:
    tags:
      - v**
jobs:
  create-release:
    name: "Create release"
    runs-on: ubuntu-latest
    env:
      ARCHIVE: nc-share-tools.tar.gz
      ARCHIVE_PATH: ..

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
      - name: "Create archive"
        run: tar czf ${ARCHIVE} -C ${{ github.workspace }} -X ${{ github.workspace }}/.tarignore .
        working-directory: ${{ env.ARCHIVE_PATH }}
      - name: "Create hash files"
        run: sha512sum ${ARCHIVE} | awk '{ print $1 }' > "${ARCHIVE}.sha512"
        working-directory: ${{ env.ARCHIVE_PATH }}
      - name: "Create release"
        run: gh release create ${GITHUB_REF_NAME} ${{ env.ARCHIVE_PATH }}/${ARCHIVE} ${{ env.ARCHIVE_PATH }}/${ARCHIVE}.sha512 --generate-notes --verify-tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
