name: Create release

on:
  push:
    tags:
      - v**
jobs:
  create-release:
    name: "Create release"
    runs-on: ubuntu-latest
    env:
      ARCHIVE: nc-share-tools.tar.gz

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no
      - name: "Create archive"
        run: tar czf ${ARCHIVE} -X ${{ github.workspace }}/.tarignore -C ${{ github.workspace }} .
        working-directory: ${{ runner.tmp }}
      - name: "Create hash files"
        run: sha512sum ${ARCHIVE} | awk '{ print $1 }' > "${ARCHIVE}.sha512"
        working-directory: ${{ runner.tmp }}
      - name: "Create release"
        run: gh release create ${GITHUB_REF_NAME} ${{ runner.tmp }}/${ARCHIVE} ${{ runner.tmp }}/${ARCHIVE}.sha512 --generate-notes --verify-tag
        working-directory: ${{ github.workspace }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
